version: '3.8'

services:
  todo-list-service:
    build: ./
    command: ./todo-list-service
    ports:
      - "8005:8001"
    environment:
      - CONFIG_PATH=config/config.yaml
      - DB_PASSWORD=qwerty
    depends_on:
      - todo-db
  todo-db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=todo-list-db
    ports:
      - "5436:5432"

