env: "docker"
http_server:
  host: "todo-list-service"
  port: "8001"
  timeout: 4s
  idle_timeout: 60s
db:
  username: "postgres"
  host: "todo-db"
  port: "5432"
  dbname: "todo-list-db"
  sslmode: "disable"